### ISSUE TITLE
Illegarl Character In Path with Sodium (can't launch)

### ISSUE THREAD

**Issue by ardissaps** [QuiltMC/quilt-loader#96] opened 2022-07-05 01:36 UTC
![image](https://user-images.githubusercontent.com/82106625/177232657-09d65f3b-ec39-477e-8699-ea20e2e99a13.png)

**Comment by SilverAndro** [comment] 2022-07-05 01:43
Seems the same as #90?

**Comment by ardissaps** [comment] 2022-07-05 01:46
What should I do?

**Comment by ardissaps** [comment] 2022-07-05 01:47
https://paste.atlauncher.com/view/fcf8b09e-975a-4cb5-bdb2-808669dadc34

**Comment by ardissaps** [comment] 2022-07-05 01:54
I disabled all mods one by one but Quilt keep saying those always illegal path, look like QMC is not ready for use. Very frustating. The Discord is also seems very hostile, it is my first time joining Discord server but need review before accepted ever.

**Comment by TheGlitch76** [comment] 2022-07-05 02:34
Bugs don't mean that the software isn't ready for use.

The problem is that there is brackets in the folder `[Minecraft] ATLauncher`; you'll need to rename that folder to something else (like just `ATLauncher`) for now.

Closing as duplicate of #90.

**Closed as not planned** 2022-07-05 02:34 UTC
Labels: duplicate

**Comment by ardissaps** [comment] 2022-07-05 03:28
> [Minecraft] ATLauncher

It's kind of easy management for huge folders naming per game, well that could be supported.

**Comment by SilverAndro** [comment] 2022-07-05 03:29
Yes which is why we have an open issue, so it can get fixed eventually

**Comment by ardissaps** [comment] 2022-07-05 03:30
Ok take your time, I suggest to make Discord auto accept like just average discord server. So newcomer can easily ask thing.

**Comment by ardissaps** [comment] 2022-07-05 04:03
> Bugs don't mean that the software isn't ready for use.
> 
> The problem is that there is brackets in the folder `[Minecraft] ATLauncher`; you'll need to rename that folder to something else (like just `ATLauncher`) for now.
> 
> Closing as duplicate of #90.

Still crash
https://paste.atlauncher.com/view/f1e6c641-3753-4d14-9d9d-b3ed4f39a951

**Comment by ardissaps** [comment] 2022-07-07 08:21
After change the folder name and still crashed, it look like it is problem with Keymaps (quilt compatibility), sorry! They said they will solve it eventually.
