### ISSUE TITLE
Minecraft fails to load resources on 1.5.2 and below

### ISSUE THREAD

**Issue by LostLuma** [QuiltMC/quilt-loader#339] opened 2023-07-31 22:50 UTC
Hello! I've been running a server with Quilt Loader using [OrnitheMC tooling](https://github.com/OrnitheMC) on Minecraft 1.3.2 recently and have run into an issue where the game can not read resources out of the Minecraft jar when combined with newer Java versions, and will cause chat to be unusable.

To reproduce you can run any version of the game from 1.3.2 to 1.5.2 (maybe older ones work as well, haven't tested) and type a space character in chat. You'll get kicked for sending an illegal character and unable to even re-join the server anymore as it messes up the internal state of the language loading system.

Minecraft log using modern Java: https://files.lostluma.net/ehtq4Q.txt
Compared with Java 8, which also has a non-fatal error: https://files.lostluma.net/etGsFF.txt

Running vanilla Minecraft or Fabric Loader with either Java version has neither the fatal or non-fatal error.  

The following code in `SharedConstants` ([Feather mappings](https://github.com/OrnitheMC/feather-mappings), 1.3.2) is what causes this issue:
```java
    private static String getValidChatCharString() {
        String var0 = "";

        try {
            BufferedReader var1 = new BufferedReader(new InputStreamReader(SharedConstants.class.getResourceAsStream("/font.txt"), "UTF-8"));
            String var2 = "";

            while((var2 = var1.readLine()) != null) {
                if (!var2.startsWith("#")) {
                    var0 = var0 + var2;
                }
            }

            var1.close();
        } catch (Exception var3) {
        }

        return var0;
    }

    public static final boolean isValidChatChar(char chr) {
        return chr != 167 && (VALID_CHAT_CHARACTERS.indexOf(chr) >= 0 || chr > ' ');
    }
```

Note the `|| chr > ' '`. The first character inside the `font.txt` file is a space, if it failed to load spaces are not legal to send in chat.

If there's any more information I should provide please let me know, I'm not really sure what would be useful.

**Comment by TheGlitch76** [comment] 2023-08-05 14:30
Could you try reproducing this issue on `"0.20.0-beta.7` (or whatever's latest by the time you get around to it)?
We just replaced a lot of the code that is probably causing this bug, so I wonder if it will change/resolve the issue

**Comment by LostLuma** [comment] 2023-08-05 15:52
Seems to behave exactly the same way, sadly.

**Comment by AlexIIL** [comment] 2023-08-05 18:26
Since the code discards the exception it's not easy to see what's going on - but what opening it up in a debugger shows this for the exception:

```java
java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:177)
	at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:984)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:959)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.initDataPos(ZipFileSystem.java:2386)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2328)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2278)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:333)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:376)
	at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:219)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:173)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:189)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.implReadLine(BufferedReader.java:371)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:348)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:437)
	at net.minecraft.unmapped.C_5185137.m_2792302(C_5185137.java:16)
	at net.minecraft.unmapped.C_5185137.<clinit>(C_5185137.java:28)
	at net.minecraft.unmapped.C_1567607.m_1958969(C_1567607.java:469)
	at net.minecraft.unmapped.C_0332750.m_7216666(C_0332750.java:44)
	at net.minecraft.unmapped.C_3499589.m_6155642(C_3499589.java:255)
	at net.minecraft.unmapped.C_3499589.m_6200989(C_3499589.java:15)
	at net.minecraft.unmapped.C_5510478.run(C_5510478.java:93)

```

**Comment by AlexIIL** [comment] 2023-08-05 20:58
Dammit github

**Comment by LostLuma** [comment] 2023-08-05 21:46
This is working for me now as of `0.20.0-beta.10`, thank you a lot for looking into it! 🙂
I'll keep this open though since you seem to intend for it to stay this way for now?

**Comment by AlexIIL** [comment] 2023-08-06 01:05
Oh no, I just wanted to keep it open until it worked for you - thanks for testing! I'll close it now, since the fix worked.

**Closed as completed by AlexIIL** 2023-08-06 01:05 UTC
