### ISSUE TITLE
Log Begone fails to install filters on all loggers when running on quilt

### ISSUE THREAD

**Issue by SilverAndro** [QuiltMC/quilt-loader#294] opened 2023-04-21 23:09 UTC
For unknown reasons, when [Log Begone](https://modrinth.com/mod/log-begone/version/1.0.5) is installed on quilt, the mods filter system fails to install on all loggers, resulting in some messages getting through (maybe even most?)

The mod init seems to be exactly the same on both quilt and fabric, so im not sure what could be breaking between the 2 given the lack of experience I have with the internals of Log4j

**Comment by AlexIIL** [comment] 2023-04-21 23:49
Duplicate of https://github.com/QuiltMC/quilt-loader/issues/229

**Closed as not planned by AlexIIL** 2023-04-21 23:49 UTC
