### ISSUE TITLE
[Bug] All Mods Appear as Resource Packs Under Minecraft 1.20.4

### ISSUE THREAD

**Issue by JCollins2048** [QuiltMC/quilt-loader#456] opened 2024-11-13 20:08 UTC
### Version Information
**Operating System:** Microsoft Windows 10 Pro 22H2 (19045.5011)
**_Minecraft_ version:** 1.20.4
**_Quilt Loader_ version:** 0.27.0-beta.1 

### Bug Information
**Steps to reproduce:**
1. Download the *[Quilt Client](https://quiltmc.org/en/)* and make a Loader *0.26.4* / *Minecraft* 1.20.4 installation.
(Note: This also happens with 0.27.0-beta.1 and possibly other versions.)
2. Go to the profile folder and add a compatible standalone or API mod.
(I used only API mods for the example below, but this happens with all mods.)
3. Launch this custom installation of ''Minecraft'' and go Options -> Resource Packs

**Expected behavior:**
Properly formatted mods placed in the "mods" folder shouldn't appear in the Resource Packs list.

**What's actually happening:**
All of my installed mods are appearing in the Resource Packs list.

### More Details
This is a weird one I've never seen before.  For whatever reason, if *Quilt Loader* is installed under *Minecraft* 1.20.4, then the player's installed mods appear in the Resource Packs list.  The mods, themselves, are still completely functional and whatnot, and they can be shifted around in the list, but they can't be "uninstalled" (not that I want to) and, frankly, shouldn't be there to begin with.

In addition, this particular combination messes with the `options.txt` file in weird ways:
- It creates a new variable, `quilt_available_resource_packs`, and fills it with *every single* mod and API the player has installed.
- It completely clears the value of `resourcePacks` and never writes to it, disabling the ability to save Resource Pack setups.
- `incompatibleResourcePacks` still works as is always has.

I tested *Minecraft* 1.20.2, 1.20.3, and 1.21.0 with *Quilt Loader* 0.26.4 and 0.27.0b1.  Installing *Quilt Loader* under any of these versions doesn't do this.  I don't know what it is about *Minecraft* 1.20.4 that causes this to happen, but it's really annoying and I'd like it if someone could look into this.

Thank you.

### Relevant Media
<img src="https://i.imgur.com/JO3Ryah.gif"><br>*Several API mods and their dependences in the Resource Pack listing.*

**Comment by OroArmor** [comment] 2024-11-13 20:19
Duplicate of QuiltMC/quilted-fabric-api#154. Fixed in later versions of Minecraft.

**Closed as not planned by OroArmor** 2024-11-13 20:19 UTC
