### ISSUE TITLE
ViaFabricPlus seems to break on QuiltLoader on Linux.

### ISSUE THREAD

**Issue by Earthcomputer** [QuiltMC/quilt-loader#293] opened 2023-04-19 16:48 UTC
[ViaFabricPlus](https://modrinth.com/mod/viafabricplus) seems to break on Quilt Loader.

Steps to reproduce:
1. Make sure you are on a Linux machine.
2. Install this mod along with Fabric API on a Quilt instance.
3. Start the game.
4. Try to join a server (on the same version as the client).
5. Observe a `ClassCastException`.

This mod only breaks with the specific combination of Linux + Quilt. Windows + Quilt works fine and so does Linux + Fabric. It looks like some class loader issue?

```
[17:45:29] [Server Connector #1/ERROR]: Couldn't connect to server
java.lang.ClassCastException: class io.netty.channel.epoll.EpollEventLoopGroup cannot be cast to class io.netty.channel.EventLoopGroup (io.netty.channel.epoll.EpollEventLoopGroup is in unnamed module of loader 'app'; io.netty.channel.EventLoopGroup is in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @457e2f02)
	at net.minecraft.class_2535.method_10753(class_2535.java:314) ~[transformed-mod-minecraft-v1.19.4.jar:?]
	at net.minecraft.class_412$1.run(class_412.java:78) ~[transformed-mod-minecraft-v1.19.4.jar:?]
```

**Comment by heipiao233** [comment] 2023-04-30 05:55
It seems that someone loads `EpollEventLoopGroup` at wrong time

**Comment by TheGlitch76** [comment] 2023-05-13 17:30
I cannot reproduce with Fabric API or Quilted Fabric API on NixOS.

**Comment by BogTheMudWing** [comment] 2023-05-14 18:51
I was having this same issue but it seems to be resolved now.

**Comment by TheGlitch76** [comment] 2023-05-15 17:17
Mod author closed the issue on their end, closing as resolved.
Feel free to re-open if the issue comes back up

**Closed as completed by TheGlitch76** 2023-05-15 17:17 UTC
Labels: bug

**Comment by RimuruT3mpest** [comment] 2023-06-16 17:27
ViaFabric & ViaFabricPlus both break on the latest version of Quilt up to today (0.19.2-beta.2), I still haven't bee able to find a fix.

**Comment by diaphragm-workplace** [comment] 2024-05-18 15:25
It did work for me on 1.20.1 but broke again on 1.20.2 (???)

**Comment by YV99king** [comment] 2025-05-06 14:43
from a quick reading looks like at some implementations of netty/quilt its library loads too fast/slow and gets loaded by multiple classloaders with different package management and gets a bit broken.
havent looked at the code though.
if quilt is using netty before setting its classloader (gameprovider/classloader bootstraping i think) it would probably cause it.
EDIT: actually i thought about it and it is probably caused by some weird execution path of the java libraries a temp fix until a proper fix could be found would probably be explicitly unloading that class to put it in the same module
for a proper fix maybe try to make classloader exceptions (classes that the quilt classloader won't even try to load and will automatically pass to the parent) and add to it the java classes? 
i won't be able to try anything in the near future through.
