### ISSUE TITLE
Certain legacy server versions crash while trying to load mods

### ISSUE THREAD

**Issue by Copetan** [QuiltMC/quilt-loader#251] opened 2023-02-27 08:44 UTC
When trying to load a 1.7.2 server with Quilt and a mod, [the game crashes due to a `MixinTargetAlreadyLoadedException`](https://mclo.gs/6MzSDGb). With the help of @SpaceWalkerRS, we tested on other versions and found that the same issue exists in 1.8.9, but not 1.9 nor 1.6.4.

I looked into it more deeply and found that [the log4j2.xml file in 1.7.2](https://mclo.gs/wK4uCb5) is slightly different from [the one in 1.9](https://mclo.gs/4jcBEN9); more specifically, the `packages` attribute in the `Configuration` element lists `net.minecraft` and `com.mojang` in 1.7.2, whereas 1.9 only lists `com.mojang.util`. I guess while trying to find Log4j plugins, the class loader loads every class within the listed packages, in turn loading Minecraft classes earlier than anticipated and breaking Mixin processing. (The server jar started bundling Log4j in 13w39a, any older versions don't have the class loading issue, seemingly because they don't use Log4j.)

While stepping through the code in a debugger, I found that there's a mechanism in [`KnotClassDelegate`](https://github.com/QuiltMC/quilt-loader/blob/develop/src/main/java/org/quiltmc/loader/impl/launch/knot/KnotClassDelegate.java) that restricts certain classes from being loaded, so I think this issue might have something to do with that?

**Comment by zeichenreihe** [comment] 2023-06-25 15:00
> mechanism in [KnotClassDelegate](https://github.com/QuiltMC/quilt-loader/blob/develop/src/main/java/org/quiltmc/loader/impl/launch/knot/KnotClassDelegate.java) that restricts certain classes from being loaded
I think the problem is just showing there, that's not the place to fix it.

I think it should be fixed by making log4j only load when the class loading + mixin applying is set up.
Because from my understanding of reading this, the loader does:
- log4j plugins finding loads classes for checking for logging stuff
- mixin setup is finished
- mc entry point is called

I think in this case, the log4j trying to load classes while mixin isn't ready is the problem

care should be taken in ensuring classes only attempt to load classes from the knot class loader after the knot class loader can load + apply mixins to classes

**Closed as completed** 2024-05-26 15:38 UTC
