### ISSUE TITLE
加载fabric最新版的mod时出现错误

### ISSUE THREAD

**Issue by RegulusSource** [QuiltMC/quilt-loader#177] opened 2022-12-14 13:04 UTC
![image](https://user-images.githubusercontent.com/90123607/207602575-92be7587-7e0e-4a9e-aee3-a847872d8ace.png)
加载fabric最新版的mod时出现错误

**Comment by RegulusSource** [comment] 2022-12-14 13:08
[crash-2022-12-14_24.31.02.1213-quilt_loader.txt](https://github.com/QuiltMC/quilt-loader/files/10228033/crash-2022-12-14_24.31.02.1213-quilt_loader.txt)

**Comment by SplendidAlakey** [comment] 2022-12-14 19:17
Duplicate of https://github.com/QuiltMC/quilt-loader/issues/174

**Closed as completed** 2023-01-24 08:27 UTC
