### ISSUE TITLE
server does not start

### ISSUE THREAD

**Issue by powl999** [QuiltMC/quilt-loader#398] opened 2024-01-19 21:14 UTC
[sudo] Passwort für paulk: 
Starting server... failed

exec java -Xms512M -Xmx1024M -jar ./quilt-server-launch.jar --nogui
Starting org.quiltmc.loader.impl.game.minecraft.BundlerClassPathCapture
[22:11:09] [main/INFO]: Loading Minecraft 1.20.2 with Quilt Loader 0.22.0
[22:11:09] [main/INFO]: Loading mappings: jar:file:/srv/quilt/libraries/net/fabricmc/intermediary/1.20.2/intermediary-1.20.2.jar!/mappings/mappings.tiny
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk/lib/libawt_xawt.so
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1957)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1993)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1388)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1386)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1385)
        at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1423)
        at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1397)
        at java.desktop/sun.awt.AppContext$2.run(AppContext.java:273)
        at java.desktop/sun.awt.AppContext$2.run(AppContext.java:262)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/sun.awt.AppContext.initMainAppContext(AppContext.java:262)
        at java.desktop/sun.awt.AppContext$3.run(AppContext.java:315)
        at java.desktop/sun.awt.AppContext$3.run(AppContext.java:298)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/sun.awt.AppContext.getAppContext(AppContext.java:297)
        at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:129)
        at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper.setIconFromMod(SolverErrorHelper.java:349)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper.access$000(SolverErrorHelper.java:58)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper$DependencyError.report(SolverErrorHelper.java:669)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper.reportErrors(SolverErrorHelper.java:69)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.handleSolverFailure(QuiltPluginManagerImpl.java:1402)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runSingleCycle(QuiltPluginManagerImpl.java:1298)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runInternal(QuiltPluginManagerImpl.java:1203)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.run(QuiltPluginManagerImpl.java:735)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.runPlugins(QuiltLoaderImpl.java:596)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:313)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:305)
        at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
        at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:78)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:66)
[22:11:10] [main/ERROR]: Crashed! The full crash report has been saved to ./crash-reports/crash-2024-01-19_22.11.10.3419-quilt_loader.txt
---- Quilt Loader: Critial Error Report ----
Date/Time: 2024/01/19 22:11:10.3524
Quilt Loader Version: 0.22.0

-- Error 2 --

Unhandled Throwable!

java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk/lib/libawt_xawt.so
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1957)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1993)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1388)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1386)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1385)
        at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1423)
        at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1397)
        at java.desktop/sun.awt.AppContext$2.run(AppContext.java:273)
        at java.desktop/sun.awt.AppContext$2.run(AppContext.java:262)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/sun.awt.AppContext.initMainAppContext(AppContext.java:262)
        at java.desktop/sun.awt.AppContext$3.run(AppContext.java:315)
        at java.desktop/sun.awt.AppContext$3.run(AppContext.java:298)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/sun.awt.AppContext.getAppContext(AppContext.java:297)
        at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:129)
        at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper.setIconFromMod(SolverErrorHelper.java:349)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper.access$000(SolverErrorHelper.java:58)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper$DependencyError.report(SolverErrorHelper.java:669)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper.reportErrors(SolverErrorHelper.java:69)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.handleSolverFailure(QuiltPluginManagerImpl.java:1402)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runSingleCycle(QuiltPluginManagerImpl.java:1298)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runInternal(QuiltPluginManagerImpl.java:1203)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.run(QuiltPluginManagerImpl.java:735)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.runPlugins(QuiltLoaderImpl.java:596)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:313)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:305)
        at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
        at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:78)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:66)

-- Error 1 --

The plugin that created this error (quilt_loader) forgot to call 'appendReportText'!
The next stacktrace is where the plugin created the error, not the actual error.'

java.lang.Throwable
        at org.quiltmc.loader.impl.gui.QuiltJsonGuiMessage.<init>(QuiltJsonGuiMessage.java:79)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.reportError(QuiltPluginManagerImpl.java:687)
        at org.quiltmc.loader.impl.plugin.BasePluginContext.reportError(BasePluginContext.java:88)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper$DependencyError.report(SolverErrorHelper.java:667)
        at org.quiltmc.loader.impl.plugin.SolverErrorHelper.reportErrors(SolverErrorHelper.java:69)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.handleSolverFailure(QuiltPluginManagerImpl.java:1402)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runSingleCycle(QuiltPluginManagerImpl.java:1298)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runInternal(QuiltPluginManagerImpl.java:1203)
        at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.run(QuiltPluginManagerImpl.java:735)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.runPlugins(QuiltLoaderImpl.java:596)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:313)
        at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:305)
        at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
        at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:78)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:66)

-- Plugin State --

Cycle number = 1
Cycle Step = SOLVE

Loaded Plugins (2):
 - 'quilt_loader' (Builtin)
 - 'quilted_fabric_loader' (Builtin)

---- end of report ----
[22:11:10] [main/ERROR]: For more details see the full crash report file: ./crash-reports/crash-2024-01-19_22.11.10.3419-quilt_loader.txt
Game crashed! Saved the crash report to ./crash-reports/crash-2024-01-19_22.11.10.3419-quilt_loader.txt
no server running on /tmp/tmux-953/quilt
paulk@paul-b550gamingxv2 ~ [1]>

**Comment by OroArmor** [comment] 2024-01-19 21:54
If you are running in a headless environment, make sure to add `--nogui` to the program arguments

**Comment by AlexIIL** [comment] 2024-01-19 22:16
Actually this is a strange issue when using a non-headless jvm in a headless environment? I've added a fix to the gui improvements in #385 though, since we don't really need to load images from bytes. (The cause of the crash is in `SolverErrorHelper.setIconFromMod(SolverErrorHelper.java:349)`)

**Comment by eristhea** [comment] 2024-08-24 19:47
this issue should be fixed. please reopen if you can still reproduce!

**Closed as completed by eristhea** 2024-08-24 19:47 UTC
Labels: bug
