### ISSUE TITLE
Server crashes with beta 58 "Cannot instantiate mods when not frozen!"

### ISSUE THREAD

**Issue by JulianVennen** [QuiltMC/quilt-loader#220] opened 2023-01-24 12:48 UTC
The latest quilt loader beta crashes on all Minecraft versions.
Example log from 1.19.3: https://mclo.gs/1ONGQSD

This was tested on a completely new installation without any mods or an existing world.

**Comment by SplendidAlakey** [comment] 2023-01-24 12:54
Duplicate of #218

**Closed as completed** 2023-01-26 13:56 UTC
