### ISSUE TITLE
(Dev only/Architectury) Fail to find mixin files on any 0.18.1 beta.

### ISSUE THREAD

**Issue by ghost** [QuiltMC/quilt-loader#231] opened 2023-01-30 19:12 UTC
We're using architectury as a build tool and it generates fake mods for each common project this seems to be causing issues with loader as the mixins from common projects aren't located in our main mod jar.

```
[18:55:10] [main/ERROR] (Quilt Loader) Uncaught exception in thread "main"
 java.lang.RuntimeException: Error creating Mixin config ellemes-container-library-thread.mixins.json for mod expandedstorage
	at org.quiltmc.loader.impl.launch.common.QuiltMixinBootstrap.init(QuiltMixinBootstrap.java:118) ~[quilt-loader-0.18.1-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:147) ~[quilt-loader-0.18.1-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70) ~[quilt-loader-0.18.1-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) ~[quilt-loader-0.18.1-beta.1.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217) ~[architectury-transformer-5.2.72-runtime.jar:5.2.72]
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config #expandedstorage:ellemes-container-library-thread.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.common.QuiltMixinBootstrap.init(QuiltMixinBootstrap.java:116) ~[quilt-loader-0.18.1-beta.1.jar:?]
	... 5 more
Caused by: java.lang.IllegalArgumentException: The specified resource '#expandedstorage:ellemes-container-library-thread.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.common.QuiltMixinBootstrap.init(QuiltMixinBootstrap.java:116) ~[quilt-loader-0.18.1-beta.1.jar:?]
	... 5 more
```

**Comment by AlexIIL** [comment] 2023-02-15 02:02
Okay this should be fixed in beta ~~77~~ 78 - sorry for the wait!

This was caused by a new "feature", which restricts where mixin files can be loaded from to the mod that declared them - this fixed a few cases of mods shipping `example.mixins.json` files but only one of them being loaded.

This fix for *this* bug was to fallback to searching everywhere if a file wasn't found, rather than failing.

**Comment by ghost** [comment] 2023-02-15 21:38
Can confirm build 78 fixes the issue for me and correctly logs warnings about the mixins being in an odd place, tysm for patching it.

```
[21:36:23] [main/WARN] (Quilt Loader) Failed to find the resource 'ellemes-container-library-thread.mixins.json' in mod 'expandedstorage', but did find it in a different place: quilt.zfs://transformed-mod-generated-40c1833.i0:0/ellemes-container-library-thread.mixins.json
[21:36:23] [main/WARN] (Quilt Loader) Failed to find the resource 'expandedstorage-common.mixins.json' in mod 'expandedstorage', but did find it in a different place: quilt.zfs://transformed-mod-generated-b1183df.i0:0/expandedstorage-common.mixins.json
[21:36:23] [main/WARN] (Quilt Loader) Failed to find the resource 'expandedstorage-thread.mixins.json' in mod 'expandedstorage', but did find it in a different place: quilt.zfs://transformed-mod-generated-40c1833.i0:0/expandedstorage-thread.mixins.json
```

**Closed as completed** 2023-02-18 23:44 UTC
Labels: bug
