### ISSUE TITLE
[dev enhancement] git tag releases on dev branch

### ISSUE THREAD

**Issue by Merith-TK** [QuiltMC/quilt-loader#313] opened 2023-05-18 15:56 UTC
Tag releases in dev branch

I only ask that when you make a release, you just run `git tag v<version>` on the *dev branch* so that way people can see all of the commits in a short summery between releases, or view the source code at a specific release with ease

https://git-scm.com/book/en/v2/Git-Basics-Tagging

You can also setup github (and gitlab) actions to run when an new "release" tag is made, this would make it so you would not need a seperate *release* branch

**Comment by Merith-TK** [comment] 2023-05-18 16:45
even made a script that will do the work for you guys
1. checkout develop branch to latest commit (`git checkout develop`)
2. paste this into an file at the root of the repo
3. run it
```sh
#!/bin/bash


# get the current branch
branch=$(git rev-parse --abbrev-ref HEAD)
## if the branch is a detached head, exit with an error
if [ "$branch" == "HEAD" ]; then
	echo "error: you are in a detached head state"
	echo "please checkout a branch and try again"
	exit 1
fi

LASTVERSION=""
# get all commits that modified the file ./gradlew.properties
echo "tagging commits"
echo "this may take a while"
git log --pretty=format:"%h" --follow -- ./gradle.properties | while read commit_hash; do
	git checkout $commit_hash >/dev/null 2>&1

	# get the version from the file ./gradlew.properties
	version=$(grep "quilt_loader " ./gradle.properties | cut -d'=' -f2)
	version=$(echo $version | sed -e 's/^[[:space:]]*//')

	## This script will only go so far back in history, and cannot go to before the refactoring of the gradle.properties file
	## otherwise it will hang until it is done searching

	# if the version is not empty and is different from the last version and the tag does not already exist
	if [ ! -z "$version" ] && [ "$version" != "$LASTVERSION" ] && [ -z "$(git tag -l v$version)" ]; then
		echo "tagging $commit_hash as v$version"
		git tag -a v$version -m "version $version"
		LASTVERSION=$version
	fi
done

echo "resetting to $branch"
git checkout $branch
echo ""
echo "tagging complete"
```

![image](https://github.com/QuiltMC/quilt-loader/assets/10422110/4e51d27e-0f72-48c3-9f2c-aed61c8044d5)
![image](https://github.com/QuiltMC/quilt-loader/assets/10422110/e359c628-8c86-4881-aadd-f33fb5442a27)


after its done, just `git push --tags` and all of the tags will upload

**Comment by Merith-TK** [comment] 2023-06-08 21:57
Bumping

**Comment by AlexIIL** [comment] 2023-06-08 22:32
I don't think we built every version against the same commit that changed the version, so we'd need to instead manually match up the commit with the [Release Github Action](https://github.com/QuiltMC/quilt-loader/actions/workflows/release.yml) which was used to build it.

**Comment by AlexIIL** [comment] 2023-06-08 22:33
> this would make it so you would not need a separate release branch

We use a separate `release` branch so we can push bugfixes to the current non-beta version rather than just target the latest.

**Comment by AlexIIL** [comment] 2023-06-08 22:52
Thanks for the reminder though! This should definitely happen - at least for new releases since adding that code should be a lot easier then manually going back and tagging every release.

**Comment by Merith-TK** [comment] 2023-06-08 23:03
This script should be useful for the `release` branch either way as it makes it easier to a degree

**Comment by AlexIIL** [comment] 2023-06-11 00:20
Sorry I didn't check this earlier - but this is actually a duplicate of #111.

**Closed as not planned by AlexIIL** 2023-06-11 00:20 UTC
Labels: enhancement

**Comment by AlexIIL** [comment] 2023-06-11 01:50
I've gone through and created tags based on the `Release` action - although I haven't made anything to do this automatically for new versions yet.

**Comment by Merith-TK** [comment] 2023-06-11 03:19
You dont need to automatically tag them, you just need to tag them

alot of systems have it setup so that when an tag is pushed, it will build and release it, like (vX.Y.Z-rel), it will detect the `-rel` or `-rcX` and make an release for it
