### ISSUE TITLE
Recent Beta versions not showing error window, instead puts different error in logs

### ISSUE THREAD

**Issue by Fnige** [QuiltMC/quilt-loader#224] opened 2023-01-27 09:18 UTC
Loader: 0.18.1 beta 60
Minecraft: 1.19.2
OS: Fedora Workstation 37 on Xorg (Pretty sure it happens on wayland too)

When launching the game with missing dependencies, the game stops because of said missing dependencies but the missing dependencies window never shows up. Instead showing this error

```---- end of report ----
[20:06:49] [main/ERROR]: For more details see the full crash report file: /home/fnige/.local/share/PrismLauncher/instances/Funny half size pack/.minecraft/crash-reports/crash-2023-01-27_20.06.49.4381-quilt_loader.txt
Exception caught from launcher
java.lang.Error: Why would you set the warning level multiple times?
	at org.quiltmc.loader.impl.gui.QuiltJsonGui$QuiltStatusNode.setWarningLevel(QuiltJsonGui.java:677)
	at org.quiltmc.loader.impl.plugin.gui.TempQuilt2OldStatusNode.toNode(TempQuilt2OldStatusNode.java:76)
	at org.quiltmc.loader.impl.plugin.gui.TempQuilt2OldStatusNode.toNode(TempQuilt2OldStatusNode.java:94)
	at org.quiltmc.loader.impl.plugin.gui.TempQuilt2OldStatusNode.toNode(TempQuilt2OldStatusNode.java:86)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.runPlugins(QuiltLoaderImpl.java:577)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:270)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:262)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:147)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Exiting with ERROR
```

Full log if needed: https://gist.github.com/FnigePython/1fd2c3c52b9c8b69e6b7bf77d9a85e1c

**Comment by AlexIIL** [comment] 2023-01-28 04:13
Okay, this should be fixed in beta 63.

**Comment by TheGlitch76** [comment] 2023-02-13 00:45
Seems to be fixed, can no longer reproduce.

**Closed as completed by TheGlitch76** 2023-02-13 00:45 UTC
